### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by barl0g** [SuperZombi/HdRezkaApi#10]
Что-то работать перестало. Раньше работало. Может я что-то не так делаю?

```
$ python test.py 
Traceback (most recent call last):
  File "/home/user/www/hdrezka/test.py", line 6, in <module>
    print(rezka.name)
  File "/home/user/miniconda3/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/user/miniconda3/lib/python3.10/site-packages/HdRezkaApi/__init__.py", line 46, in name
    return self.soup.find(class_="b-post__title").get_text().strip()
AttributeError: 'NoneType' object has no attribute 'get_text'
```

Вот так тестировал.

```
$ cat test.py 
from HdRezkaApi import *

url = "http://<hdrezka_url>/films/action/6402-krikuny-1995.html"

rezka = HdRezkaApi(url)
print(rezka.name)
print( rezka.translators )
print( rezka.getStream()('720p') ) # if movie
print( rezka.getStream('1', '1')('720p') )
```

**Comment by SuperZombi** [comment]
VPN?

**Comment by SuperZombi** [comment]
Ні. Знаєш чому? Тому що дзеркала просять вход.
![{C200CDE1-2505-40F5-A6BC-D6C8B07C4C51}](https://github.com/user-attachments/assets/aaecdddf-d6d9-4b45-a2d0-73da5bc258aa)

**Comment by barl0g** [comment]
> VPN?

Нет. Зеркало.

**Comment by barl0g** [comment]
> Ні. Знаєш чому? Тому що дзеркала просять вход. ![{C200CDE1-2505-40F5-A6BC-D6C8B07C4C51}](https://private-user-images.githubusercontent.com/75096786/394894901-aaecdddf-d6d9-4b45-a2d0-73da5bc258aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTYyOTUsIm5iZiI6MTczMzk5NTk5NSwicGF0aCI6Ii83NTA5Njc4Ni8zOTQ4OTQ5MDEtYWFlY2RkZGYtZDZkOS00YjQ1LWEyZDAtNzNkYTViYzI1OGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDA5MzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZWViZDFkYTZmZmI0NjMwYTcxZTA3ZDk2ZjA3MTA5MDE5OGY4Zjg0ODk1Y2EwNGY4MDVlOTI3NmVhYWNhNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v3CtsqiENdWam6-ctH1JZ0tsQR8f0rMdwUpw7MRIIH4)

Получается, что сейчас работает только с URL: hdrezka.ag?

**Comment by SuperZombi** [comment]
Fixed in [`7.2.0`](https://github.com/SuperZombi/HdRezkaApi/releases/tag/7.2)
