### ISSUE TITLE
Сделай фильтр на clearTrash, чтобы он не кушал boolean

### ISSUE THREAD

**Issue by Bogdan0w** [SuperZombi/HdRezkaApi#3]
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    bot.polling(none_stop=True)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 485, in polling
    self.__threaded_polling(none_stop, interval, timeout, long_polling_timeout)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 544, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 507, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 117, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "main.py", line 53, in handle_callback
    stream = rezka.getStream(1, 5)
  File "/usr/local/lib/python3.8/dist-packages/HdRezkaApi/__init__.py", line 267, in getStream
    return getStreamMovie(self, tr_id)
  File "/usr/local/lib/python3.8/dist-packages/HdRezkaApi/__init__.py", line 238, in getStreamMovie
    return makeRequest({
  File "/usr/local/lib/python3.8/dist-packages/HdRezkaApi/__init__.py", line 198, in makeRequest
    arr = self.clearTrash(r['url']).split(",")
  File "/usr/local/lib/python3.8/dist-packages/HdRezkaApi/__init__.py", line 99, in clearTrash
    arr = data.replace("#h", "").split("//_//")
AttributeError: 'bool' object has no attribute 'replace'

**Comment by SuperZombi** [comment]
Не совсем понимаю из-за чего возникла ошибка.
Покажите свой код

**Comment by Bogdan0w** [comment]
К сожалению полный код я не могу показать. Ошибка возникает из-за данной строки "bot.polling(none_stop=True)", содержащий boolean, который HDRezkaApi пытаеться прогнать через clearTrash

**Comment by SuperZombi** [comment]
К сожалению я не понимаю что вы пытаетесь сделать. Либо отправьте полный код либо прочитайте документацию библиотеки.
Bot poling это команда телеграм бота, а не моей библиотеки.

**Comment by 10kkm** [comment]
это во всех либах по HdRezka, когда используешь не на домашнем пк, закинул на вдс не работает, с домашнего пк работает, от системы не зависит, очень интересно)

**Comment by 10kkm** [comment]
Проблема не в коде, а в приколе АПИ хдрезки, единственное что известно, это то что проблема тут от либы -> 
```py
    @staticmethod
    def clearTrash(data):
        trashList = ["@", "#", "!", "^", "$"]
        trashCodesSet = []
        for i in range(2, 4):
            startchar = ""
            for chars in product(trashList, repeat=i):
                data_bytes = startchar.join(chars).encode("utf-8")
                trashcombo = base64.b64encode(data_bytes)
                trashCodesSet.append(trashcombo)
        print(data)
        arr = data.replace("#h", "").split("//_//")
        trashString = "".join(arr)

        for i in trashCodesSet:
            temp = i.decode("utf-8")
            trashString = trashString.replace(temp, "")

        finalString = base64.b64decode(trashString + "==")
        return finalString.decode("utf-8")
```
